# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Java CI with Maven

on: [push, pull_request]

jobs:
  build-storm-on-s390x:
    runs-on: ${{ matrix.os }}
    name: Build on ubuntu-18.04 s390x
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 11, 17, 21 ]
        module: [ Client, Server, Core, External, Check-Updated-License-Files, Integration-Test ]
        experimental: [false]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: uraimo/run-on-arch-action@v2.7.1
        with:
          arch: s390x
          distro: ubuntu22.04
          githubToken: ${{ github.token }}
          install: |
            sudo apt-get update -q -y
            sudo apt-get install -y ruby nodejs python3 maven

          run: |
            uname -a
            echo "Nodejs version is : "
            nodejs --version
            echo "Ruby version is : "
            ruby --version
            echo "Maven version is : "
            maven --version
            echo "Python version is : "
            python3 -V
            
      - name: Get the output
        run: |
          uname -a 
